STRWEB-94 lock esbuild-loader to ~3.0.0 (#116)
`esbuild-loader` `v3.1.0` causes build failures in platform-complete
across many modules with complaints like,
```
ERROR in ./node_modules/@folio/data-import/src/components/DataFetcher/DataFetcher.js
Module build failed (from ./node_modules/esbuild-loader/dist/index.cjs):
Error: Transform failed with 1 error:
/Users/zburke/temp/platform-complete/node_modules/@folio/data-import/src/components/DataFetcher/DataFetcher.js:59:0:
ERROR: Transforming JavaScript decorators to the configured target environment ("es2015") is not supported yet
    at failureErrorWithLog (/Users/zburke/temp/platform-complete/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/zburke/temp/platform-complete/node_modules/esbuild/lib/main.js:847:29
    at responseCallbacks.<computed> (/Users/zburke/temp/platform-complete/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/Users/zburke/temp/platform-complete/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/Users/zburke/temp/platform-complete/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
 @ ./node_modules/@folio/data-import/src/components/DataFetcher/index.js 1:0-30 1:0-30
 @ ./node_modules/@folio/data-import/src/components/index.js 11:0-30 11:0-30
 @ ./node_modules/@folio/data-import/src/index.js 41:0-44:22 54:104-132 60:49-60
 @ ./node_modules/stripes-config.js
```

Refs STRWEB-94

(cherry picked from commit 8ef846a130b5d42be842cdaae6796febd5edb73d)