STRWEB-105 lock favicons to v7.1.4 to avoid build failures (#135)
`favicons` `v7.1.5` bumps `sharp` from `v0.32.6` to `v0.33.1` and ain't
nothin' building anymore. See also https://github.com/itgalaxy/favicons/issues/448.
Jenkins errors look like
```
/home/jenkins/workspace/Automation/build-platform-complete-snapshot/node_modules/favicons-webpack-plugin/src/index.js:656
    throw new Error(
          ^

Error: Could not find the npm peerDependency "favicons".
Please run:
npm i favicons
 - or -
yarn add favicons

Error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
    npm install --force @img/sharp-linux-x64
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at loadFaviconsLibrary (/home/jenkins/workspace/Automation/build-platform-complete-snapshot/node_modules/favicons-webpack-plugin/src/index.js:656:11)
    at #generateFaviconsWebapp (/home/jenkins/workspace/Automation/build-platform-complete-snapshot/node_modules/favicons-webpack-plugin/src/index.js:454:26)
    at #generateFavicons (/home/jenkins/workspace/Automation/build-platform-complete-snapshot/node_modules/favicons-webpack-plugin/src/index.js:376:44)
    at /home/jenkins/workspace/Automation/build-platform-complete-snapshot/node_modules/favicons-webpack-plugin/src/index.js:164:42
    at /home/jenkins/workspace/Automation/build-platform-complete-snapshot/node_modules/favicons-webpack-plugin/src/cache.js:150:5
    at CacheFacade.providePromise (/home/jenkins/workspace/Automation/build-platform-complete-snapshot/node_modules/webpack/lib/CacheFacade.js:341:24)

Node.js v18.17.1
error Command failed with exit code 1.
```
and similar errors occur in local development builds in other OSes.

Refs STRWEB-105

(cherry picked from commit 7b54dd8efd2ac5b91f67983ff122a0e7e95a7ea5)